[package]
name = "playground_picky"
version = "0.1.0"
edition = "2021"

[dependencies]
tokenizers_picky = {version = "0.20.1-dev.0", path = "../tokenizers"}
clap = { version = "4.0", features = ["derive"] } 

